export const PREFIX = 'EP.'

function addPrefix(param) {
  return PREFIX + param
}

export const EYE_RESULTS = PREFIX + 'EYE_RESULTS'
export const FACE_RESULTS = PREFIX + 'FACE_RESULTS'
export const HAND_RESULTS = PREFIX + 'HAND_RESULTS'
export const BODY_RESULTS = PREFIX + 'BODY_RESULTS'
export const APPEAR_RESULTS = PREFIX + 'APPEAR_RESULTS'
export const SENTENCE_RESULTS = PREFIX + 'SENTENCE_RESULTS'
export const WORD_RESULTS = PREFIX + 'WORD_RESULTS'
export const VOCAL_RESULTS = PREFIX + 'VOCAL_RESULTS'
export const PAUSES_RESULTS = PREFIX + 'PAUSES_RESULTS'
export const DISFLUENCY_RESULTS = PREFIX + 'DISFLUENCY_RESULTS'
export const MODULATION_RESULTS = PREFIX + 'MODULATION_RESULTS'
export const STORE_INTERVIEW_KEYS = PREFIX + 'STORE_INTERVIEW_KEYS'
export const INITIALIZE_RESULTS = PREFIX + 'INITIALIZE_RESULTS'
export const STORE_SAVE_AUDIO_RESULTS = PREFIX + 'STORE_SAVE_AUDIO_RESULTS'
export const SET_APP_URLS = PREFIX + 'SET_APP_URLS'
export const CONVERT_VIDEO_RESULTS = PREFIX + 'CONVERT_VIDEO_RESULTS'
export const STATUSES = PREFIX + 'APP_STATUSES'
export const SET_TRANSCRIPT = PREFIX + 'SET_TRANSCRIPT'
export const TOTAL_RESULT = PREFIX + 'TOTAL_RESULT'
export const SET_VIDEO_TYPE = PREFIX + 'SET_VIDEO_TYPE'
export const VIDEO_FLOATING = PREFIX + 'VIDEO_FLOATING'
export const REGULAR_VIDEO_STATE = PREFIX + 'REGULAR_VIDEO_STATE'
export const FlOATING_VIDEO_STATE = PREFIX + 'FlOATING_VIDEO_STATE'
export const VIDEO_FLOATING_PLAYING = PREFIX + 'VIDEO_FLOATING_PLAYING'
export const FINAL_CALIBRATION_ID = PREFIX + 'FINAL_CALIBRATION_ID'
export const COMP_VIDEO_CHUNKS_DATA = PREFIX + 'COMP_VIDEO_CHUNKS_DATA'
export const VIDEO_CHUNKS_VISIBLE = PREFIX + 'VIDEO_CHUNKS_VISIBLE'
export const VIDEO_CHUNKS_STATE = PREFIX + 'VIDEO_CHUNKS_STATE'
export const INFOBARS_ANIMATION_STATE = PREFIX + 'INFOBARS_ANIMATION_STATE'
export const FETCH_ILLUSTRATION_DATA = PREFIX + 'FETCH_ILLUSTRATION_DATA'
export const TAB_INDEX = PREFIX + 'TAB_INDEX'
export const EP_CUSTOMIZATIONS = PREFIX + 'EP_CUSTOMIZATIONS'

export const actionLabels = {
  EYE_RESULTS: addPrefix('EYE_RESULTS'),
  FACE_RESULTS: addPrefix('FACE_RESULTS'),
  HAND_RESULTS: addPrefix('HAND_RESULTS'),
  BODY_RESULTS: addPrefix('BODY_RESULTS'),
  APPEAR_RESULTS: addPrefix('APPEAR_RESULTS'),
  SENTENCE_RESULTS: addPrefix('SENTENCE_RESULTS'),
  WORD_RESULTS: addPrefix('WORD_RESULTS'),
  VOCAL_RESULTS: addPrefix('VOCAL_RESULTS'),
  PAUSES_RESULTS: addPrefix('PAUSES_RESULTS'),
  DISFLUENCY_RESULTS: addPrefix('DISFLUENCY_RESULTS'),
  MODULATION_RESULTS: addPrefix('MODULATION_RESULTS'),
  STORE_INTERVIEW_KEYS: addPrefix('STORE_INTERVIEW_KEYS'),
  INITIALIZE_RESULTS: addPrefix('INITIALIZE_RESULTS'),
  STORE_SAVE_AUDIO_RESULTS: addPrefix('STORE_SAVE_AUDIO_RESULTS'),
  SET_APP_URLS: addPrefix('SET_APP_URLS'),
  CONVERT_VIDEO_RESULTS: addPrefix('CONVERT_VIDEO_RESULTS'),
  STATUSES: addPrefix('APP_STATUSES'),
  SET_TRANSCRIPT: addPrefix('SET_TRANSCRIPT'),
  TOTAL_RESULT: addPrefix('TOTAL_RESULT'),
  SET_VIDEO_TYPE: addPrefix('SET_VIDEO_TYPE'),
  VIDEO_FLOATING: addPrefix('VIDEO_FLOATING'),
  REGULAR_VIDEO_STATE: addPrefix('REGULAR_VIDEO_STATE'),
  FlOATING_VIDEO_STATE: addPrefix('FlOATING_VIDEO_STATE'),
  VIDEO_FLOATING_PLAYING: addPrefix('VIDEO_FLOATING_PLAYING'),
  FINAL_CALIBRATION_ID: addPrefix('FINAL_CALIBRATION_ID'),
  COMP_VIDEO_CHUNKS_DATA: addPrefix('COMP_VIDEO_CHUNKS_DATA'),
  VIDEO_CHUNKS_VISIBLE: addPrefix('VIDEO_CHUNKS_VISIBLE'),
  VIDEO_CHUNKS_STATE: addPrefix('VIDEO_CHUNKS_STATE'),
  INFOBARS_ANIMATION_STATE: addPrefix('INFOBARS_ANIMATION_STATE'),
  FETCH_ILLUSTRATION_DATA: addPrefix('FETCH_ILLUSTRATION_DATA'),
  TAB_INDEX: addPrefix('TAB_INDEX'),
  EP_CUSTOMIZATIONS: addPrefix('EP_CUSTOMIZATIONS'),
  //interview actions below
  VIDEO_PROCESSED_PERCENT: addPrefix('VIDEO_PROCESSED_PERCENT'),
  INTERVIEW_DURATION: addPrefix('INTERVIEW_DURATION'),
  INTERVIEW_NAME: addPrefix('INTERVIEW_NAME'),
  INTERVIEW_QUESTION_ID: addPrefix('INTERVIEW_QUESTION_ID'),
  INTERVIEW_FAVOURITE_STATUS: addPrefix('INTERVIEW_FAVOURITE_STATUS'),
}
